on: [push,pull_request]
jobs:
  maanam:
   steps: 
     - run: echo Hello World
     - uses: actions/checkout@v2
     - run: g++ -o main Liczby_Losowe.cpp
     - run: ./main
   runs-on: ${{matrix.platform}}
   strategy: 
     matrix: 
       platform: [ubuntu-latest,macos-latest,windows-latest]
