on: [push,pull_request]
jobs:
  maanam:
   steps: 
     - run: echo Hello World
   runs-on: ${{matrix.platform}}
   strategy: 
     matrix: 
       platform: [ubuntu-latest,macos-latest,windows-latest]
